name: markdown_quill
description: Convert between quill (delta) format and markdown
version: 1.0.0
repository: https://github.com/TarekkMA/markdown_quill

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  charcode: ^1.3.1
  flutter_quill: ^7.1.20
  markdown: 7.0.1

dependency_overrides:
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  meta:
  very_good_analysis:
